from typing import List, Optional
from datetime import datetime, timezone
from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.database import get_db
from src.models.entities import SuggestionModel, ReviewModel, PostModel, ImageModel
from src.schemas.review import ReviewCreate, ReviewResponse

router = APIRouter(prefix="/review", tags=["Review Workflow"])

@router.get("/suggestions")
async def list_suggestions(
    post_id: Optional[str] = Query(None),
    guard_status: Optional[str] = Query(None, description="'APPROVED' or 'REJECTED'"),
    limit: int = Query(50, ge=1, le=100),
    offset: int = Query(0, ge=0),
    session: AsyncSession = Depends(get_db)
):
    """List pairing suggestions generated by the system for inspection."""
    query = select(SuggestionModel, PostModel, ImageModel).join(
        PostModel, SuggestionModel.post_id == PostModel.id
    ).join(
        ImageModel, SuggestionModel.image_id == ImageModel.id
    )

    if post_id:
        query = query.where(SuggestionModel.post_id == post_id)
    if guard_status:
        query = query.where(SuggestionModel.guard_status == guard_status.upper())

    query = query.order_by(SuggestionModel.created_at.desc()).offset(offset).limit(limit)
    res = await session.execute(query)
    rows = res.all()

    items = []
    for sug, post, img in rows:
        items.append({
            "suggestion_id": sug.id,
            "post_id": post.id,
            "post_title": post.title,
            "image_id": img.id,
            "image_filename": img.filename,
            "image_caption": img.caption,
            "image_subject": img.subject,
            "rank": sug.rank,
            "similarity_score": sug.similarity_score,
            "guard_status": sug.guard_status,
            "rejection_reason": sug.rejection_reason,
            "created_at": sug.created_at
        })
    return items

@router.get("/suggestions/{suggestion_id}")
async def get_suggestion(suggestion_id: str, session: AsyncSession = Depends(get_db)):
    """Inspect why a specific image suggestion was selected or refused."""
    query = select(SuggestionModel, PostModel, ImageModel).join(
        PostModel, SuggestionModel.post_id == PostModel.id
    ).join(
        ImageModel, SuggestionModel.image_id == ImageModel.id
    ).where(SuggestionModel.id == suggestion_id)

    res = await session.execute(query)
    row = res.first()
    if not row:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Suggestion '{suggestion_id}' not found"
        )
    sug, post, img = row
    return {
        "suggestion_id": sug.id,
        "post": {
            "id": post.id,
            "title": post.title,
            "content": post.content,
            "expected_category": post.expected_category
        },
        "image": {
            "id": img.id,
            "filename": img.filename,
            "category": img.category,
            "subject": img.subject,
            "caption": img.caption,
            "confidence": img.confidence,
            "status": img.status
        },
        "rank": sug.rank,
        "similarity_score": sug.similarity_score,
        "guard_status": sug.guard_status,
        "rejection_reason": sug.rejection_reason,
        "created_at": sug.created_at
    }

@router.post("/suggestions/{suggestion_id}", response_model=ReviewResponse, status_code=status.HTTP_201_CREATED)
async def submit_review(
    suggestion_id: str,
    payload: ReviewCreate,
    session: AsyncSession = Depends(get_db)
):
    """
    Human-in-the-loop review: Approve or reject a suggested pairing.
    Records human audit decision into the reviews database table.
    """
    sug_query = select(SuggestionModel).where(SuggestionModel.id == suggestion_id)
    suggestion = (await session.execute(sug_query)).scalar_one_or_none()
    if not suggestion:
        raise HTTPException(status_code=404, detail=f"Suggestion '{suggestion_id}' not found")

    new_review = ReviewModel(
        suggestion_id=suggestion.id,
        post_id=suggestion.post_id,
        image_id=suggestion.image_id,
        decision=payload.decision,
        notes=payload.notes,
        reviewed_at=datetime.now(timezone.utc)
    )
    session.add(new_review)
    await session.commit()
    await session.refresh(new_review)
    return new_review

@router.get("/history", response_model=List[ReviewResponse])
async def list_review_history(
    limit: int = Query(50, ge=1, le=100),
    session: AsyncSession = Depends(get_db)
):
    """Retrieve full log of human-in-the-loop review actions."""
    query = select(ReviewModel).order_by(ReviewModel.reviewed_at.desc()).limit(limit)
    res = await session.execute(query)
    return res.scalars().all()
